# Your Solution
version: '3'
services:
  book_catalog:
    image: book_catalog:1
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    platform: linux/amd64
    ports:
    - "8000:8000"
    environment: 
    - DATABASE_URL=postgresql://sit722_7_2p_5w04_user:DfYz0iMBvwTwxUltA6XVgL0fcm2wBlyd@dpg-cs37lud6l47c73ebb9b0-a.oregon-postgres.render.com/sit722_7_2p_5w04

  inventory_management:
    image: inventory_management:1
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    platform: linux/amd64
    ports:
      - "8001:8001"
    environment: 
     - DATABASE_URL=postgresql://sit722_7_2p_5w04_user:DfYz0iMBvwTwxUltA6XVgL0fcm2wBlyd@dpg-cs37lud6l47c73ebb9b0-a.oregon-postgres.render.com/sit722_7_2p_5w04
